### ISSUE TITLE
请问DPO是否支持全参数训练？

### ISSUE THREAD

**Issue by jdmdj1999** [mst272/LLM-Dojo#1]

**Comment by mst272** [comment]
已支持， train_mode选择‘full’即可

**Comment by jdmdj1999** [comment]
非常感谢，请问如果想使用多轮对话进行DPO训练，数据集的格式是什么呢？
./data/dpo_multi_data.jsonl中chosen和rejected只是对prompt中的问题进行了两次回答，以Qwen-Chat模型为例是否可以进行多轮对话的DPO呢？

**Comment by mst272** [comment]
> 非常感谢，请问如果想使用多轮对话进行DPO训练，数据集的格式是什么呢？ ./data/dpo_multi_data.jsonl中chosen和rejected只是对prompt中的问题进行了两次回答，以Qwen-Chat模型为例是否可以进行多轮对话的DPO呢？

示例数据中以chosen为例，进行了两次 user 和 assistant的问答，可以按照此格式构建
