### ISSUE TITLE
训练后的模型转换问题

### ISSUE THREAD

**Issue by wf-willmer** [mst272/LLM-Dojo#14]
我在训练后的模型输出目录中，尝试执行模型转换。参考https://github.com/ggerganov/llama.cpp  。执行 llama.cpp convert_hf_to_gguf.py /home/LLM-Dojo/llmout --outtype f16 发现config文件好像不正确。
然后重新进行模型训练查看过程输出内容发现如下警告。
 warnings.warn(
/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in /home/Qwen2-0.5B-Instruct - will assume that the vocabulary was not modified.
不确定是否是因为这个警告导致，在我下载的Qwen2-0.5B-Instruct目录下存在如下内容：config.json  generation_config.json  LICENSE  merges.txt  model.safetensors  README.md  tokenizer_config.json  tokenizer.json  vocab.json。
我训练后输入目录下如下内容：
adapter_config.json  adapter_model.safetensors  all_results.json  checkpoint-1  README.md  runs  trainer_state.json  training_args.bin  train.log  train_results.json
所以想问下，训后的模型如果进行模型转换导入ollama使用，是不是我的方式或者理解有问题，如果需要对输出后文件做一些手工处理，麻烦给与一定帮助，非常感谢！

**Comment by mst272** [comment]
你是不是没合并lora权重

**Comment by wf-willmer** [comment]
抱歉，没注意到相关内容，问题解决，非常感谢！
