### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by jswjc555** [mst272/LLM-Dojo#16]
按照步骤一步步来，最后python main.py的时候，说有参数在cpu上。
![image](https://github.com/user-attachments/assets/f460fca2-015d-45fd-84ec-f4f0fb02cb5b)
    然后注意到100行有注释fix bug，设置device_map为auto，我把注释打掉之后报错
![image](https://github.com/user-attachments/assets/f9f64727-51ee-482e-895c-7a866f2eaece)
     请问，有遇到过相似的问题吗

**Comment by mst272** [comment]
请贴一下更详细的训练信息， 有可能是环境问题torch== 2.2.2，deepspeed== 0.14.2试一下

**Comment by jswjc555** [comment]
感谢回复，我后续重新构建conda环境并用deepspeed成功运行了。
我的一些额外问题是，utils下的args.py和train_args文件下配置好像没有验证集eval大小的相关参数，训练之后的wandb看板只有train_loss而没有eval_loss。train_loss呈阶梯性下降，但是没有跑出来eval_loss无法判断训练是否成功，是否是我哪里没有设置正确？
```python
 LLM-Dojo_old/utils/args.py
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


class TrainMode(Enum):
    QLORA = 'qlora'
    LORA = 'lora'
    FULL = 'full'


class TrainArgPath(Enum):
    SFT_LORA_QLORA_BASE = 'sft_args'
    DPO_LORA_QLORA_BASE = 'dpo_args'


@dataclass
class CommonArgs:
    """
    一些常用的自定义参数
    """
    # Deepspeed相关参数，如出现报错可注释掉
    local_rank: int = field(default=1, metadata={"help": "deepspeed所需参数,单机无需修改，如出现报错可注释掉"})

    train_args_path: TrainArgPath = field(default='sft_args', metadata={"help": "训练参数,分为sft和dpo参数[sft_args,dpo_args]"})
    max_len: int = field(default=1024, metadata={"help": "最大输入长度,dpo时该参数在dpo_config中设置"})
    max_prompt_length: int = field(default=512, metadata={
        "help": "dpo时，prompt的最大长度，适用于dpo_single,dpo_multi时该参数在dpo_config中设置"})
    train_data_path: Optional[str] = field(default='/mnt/f7a57ea9-f9b0-4806-966e-7f21cbc76421/yihao/llm/LLM-Dojo/data/out_dojo_sft_processed_HuatuoGPT_sft_data_vall.json',
                                            metadata={"help": "训练集路径"})
    model_name_or_path: str = field(default='/mnt/f7a57ea9-f9b0-4806-966e-7f21cbc76421/yihao/llm/langchain_RAG/model/Qwen2-7B-Instruct', 
                                            metadata={"help": "下载的所需模型路径"})

    # 微调方法相关选择与配置
    train_mode: TrainMode = field(default='lora',
                                  metadata={"help": "选择采用的训练方式：[qlora, lora, full]"})
    use_dora: bool = field(default=False, metadata={"help": "仅在train_mode==lora时可以使用。是否使用Dora(一个基于lora的变体) "
                                                            "目前只支持linear and Conv2D layers."})

    task_type: str = field(default="sft",
                           metadata={"help": "预训练任务：[pretrain, sft, dpo_multi, dpo_single]，目前支持sft,dpo"})

    # lora相关配置
    lora_rank: Optional[int] = field(default=64, metadata={"help": "lora rank"})
    lora_alpha: Optional[int] = field(default=16, metadata={"help": "lora alpha"})
    lora_dropout: Optional[float] = field(default=0.05, metadata={"help": "lora dropout"})
```

```python
# LLM-Dojo_old/train_args/sft/lora_qlora/base.py
"""
一般来说这里的参数是各个模型都通用的
"""
from dataclasses import dataclass, field
from typing import Optional, Union, List
from transformers import TrainingArguments, SchedulerType, IntervalStrategy
from transformers.training_args import OptimizerNames



@dataclass
class TrainArgument(TrainingArguments):
    """
    训练参数, 直接在这里修改default即可
    """
    output_dir: str = field(default='/mnt/f7a57ea9-f9b0-4806-966e-7f21cbc76421/yihao/llm/LLM-Dojo/sft_model_save', metadata={"help": "模型训练完成后的保存路径"})
    num_train_epochs: int = field(default=3, metadata={"help": "训练轮次"})
    per_device_train_batch_size: int = field(default=2, metadata={"help": "训练的batch size"})
    gradient_checkpointing: bool = field(default=True, metadata={"help": "是否使用梯度累计"})
    gradient_accumulation_steps: int = field(default=16, metadata={"help": "梯度累计的步长"})
    learning_rate: float = field(default=2e-4, metadata={"help": "学习率"})
    logging_steps: int = field(default=100, metadata={"help": "打印的步长"})
    save_steps: int = field(default=500, metadata={"help": "多少步长保存一次"})
    save_strategy: Union[IntervalStrategy, str] = field(default="steps", metadata={"help": "The checkpoint save "
                                                                                           "strategy to use."}, )
    save_total_limit: Optional[int] = field(default=2, metadata={"help": "保存的限制总量"})
    lr_scheduler_type: Union[SchedulerType, str] = field(default="cosine",
                                                         metadata={"help": "The scheduler type to use."})
    lr_scheduler_kwargs: dict = field(default_factory=lambda: {'num_cycles': 1},
                                      metadata={"help": "lr_scheduler的额外参数，例如 {'num_cycles': 1}"})
    warmup_steps: int = field(default=10, metadata={"help": "Linear warmup over warmup_steps."})
    optim: Union[OptimizerNames, str] = field(default='adamw_torch', metadata={"help": "The optimizer to use."})
    seed: int = field(default=42, metadata={"help": "Random seed that will be set at the beginning of training."})
    report_to: Optional[List[str]] = field(default='tensorboard', metadata={
        "help": "The list of integrations to report the results and logs to."})
    remove_unused_columns: Optional[bool] = field(default=False, metadata={
        "help": "Remove columns not required by the model when using an nlp.Dataset."})
    bf16: bool = field(default=True, metadata={
        "help": ("Whether to use bf16 (mixed) precision instead of 32-bit. Requires Ampere or higher NVIDIA"
                 " architecture or using CPU (use_cpu) or Ascend NPU. This is an experimental API and it may change."
                 )
    })
    fp16: bool = field(default=False, metadata={"help": "Whether to use fp16 (mixed) precision instead of 32-bit"})

    # Deepspeed训练相关参数，不使用时设置为default=None
    deepspeed: Optional[str] = field(default='./train_args/deepspeed_config/ds_config_zero2.json',
                                     metadata={"help": "启用Deepspeed时需要的config文件"})

```

上面是我的两个文件配置。
训练命令是`deepspeed --include localhost:0,1 main_train.py`

**Comment by mst272** [comment]
想要eval可以自行在train_args中添加eval_strategy，以及分配eval data给Trainer，因为目前训练语言大模型的话一般eval_strategy设置为no，即不进行eval。你可以先自己试一下，后续可以考虑在本框架中增加eval选项。

**Comment by mst272** [comment]
> ```shell
> device_map
> ```

如报错所示，deepspeed 的zero3 不支持使用device_map

**Comment by mst272** [comment]
> > 请贴一下更详细的训练信息， 有可能是因为你没有使用deepspeed，且没有在参数配置中注释掉deepspeed参数。
> 
> 您好 请教下： 我在训练PPO时，也遇到了训练过程中 **`有参数在cpu上`** 上的问题，但是 我将模型加载参数device_map设置auto，同时开启deepspeed后，报下面的错误：
> 
> ```shell
> Traceback (most recent call last):
>   File "/slz/LLM-Dojo/rlhf/rlhf_train.py", line 165, in main
>     reward_model = AutoModelForSequenceClassification.from_pretrained(config.reward_model_path, num_labels=1, device_map="auto",
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
>     return model_class.from_pretrained(
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3270, in from_pretrained
>     raise ValueError(
> ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.
> ```
> 
> 数据在CPU和cuda位置不匹配的错误信息如下：
> 
> ```shell
> Traceback (most recent call last):
>   File "/slz/LLM-Dojo/rlhf/rlhf_train.py", line 240, in <module>
>     main()
>   File "/slz/LLM-Dojo/rlhf/rlhf_train.py", line 234, in main
>     trainer.train()
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/trl/trainer/ppov2_trainer.py", line 443, in train
>     accelerator.backward(loss)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/accelerate/accelerator.py", line 2151, in backward
>     self.deepspeed_engine_wrapped.backward(loss, **kwargs)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 178, in backward
>     self.engine.step()
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
>     self._take_model_step(lr_kwargs)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
>     self.optimizer.step()
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2047, in step
>     self.unscale_and_clip_grads(sub_group_id, scaled_global_grad_norm)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>   File "/lh/anaconda3/envs/qwen_moe/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2117, in unscale_and_clip_grads
>     self.fp32_partitioned_groups_flat[sub_group_id].grad.mul_(1. / combined_scale)
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> ```
> 
> 启动命令如下：
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0,1,2,3 nohup accelerate launch --config_file ./ds_config/deepspeed_zero3.yaml rlhf_train.py 
> ```
> 
> 期待您的回复，谢谢！

是否是用了zero3 + QLORA？
