### ISSUE TITLE
未来会增加验证集和早停等相关功能码？

### ISSUE THREAD

**Issue by wf-willmer** [mst272/LLM-Dojo#18]
整体不太懂，只是了解了一些概念，想知道后续会增加验证集进行验证，同时是否可以支持什么早停等设置。以更好的对训练结果进行判断？

**Comment by mst272** [comment]
后续会逐步增加验证集及结果评测，在一些垂直领域的验证已经做了但还没有放出。早停设置是一个好的建议，近期应该会添加。

**Comment by wf-willmer** [comment]
ok，期待关注！
