### ISSUE TITLE
使用deepspeed zero3进行lora训练时，出现cuda所在的设备不一致报错

### ISSUE THREAD

**Issue by zeminroot** [mst272/LLM-Dojo#21]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by mst272** [comment]
是进行什么训练 详细配置信息是啥。。

**Comment by zeminroot** [comment]
> 是进行什么训练 详细配置信息是啥。。


DATA_PATH='./data/sft_data.jsonl'
OUTPUT_PATH="../train_output"
MODEL_PATH="../download_llm/qwen/Qwen2-7B-Instruct"

# deepspeed 启动
deepspeed --include localhost:0,1 main_train.py\
    --train_args_path "sft_args" \
    --train_data_path "$DATA_PATH" \
    --model_name_or_path "$MODEL_PATH" \
    --max_len 1024 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --task_type "sft" \
    --train_mode "lora" \
    --output_dir "$OUTPUT_PATH" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 5 \
    --learning_rate 1e-4 \
    --warmup_steps 10 \
    --logging_steps 1 \
    --lr_scheduler_type "linear" \
    --gradient_checkpointing True \
    --report_to "wandb" \
    --deepspeed './train_args/deepspeed_config/ds_config_zero3.json' \
    --bf16 True

**Comment by mst272** [comment]
conda环境是啥

**Comment by aJupyter** [comment]
看起来这是deepspeed没装好 看一下 `ds_report`
