### ISSUE TITLE
dpo调完结果完全错误

### ISSUE THREAD

**Issue by liulan93** [mst272/LLM-Dojo#22]
Prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：粘膜淡红色，表面散在白色斑片状物质附着，不易拭去，拭去后观察食管黏膜散在片状充血水肿，食管中下段见纵向暗蓝色静脉曲张，未见红色征及串珠样改变，齿状线清，贲门开闭正常。 胃底、胃体：胃底穹隆部见条状曲张静脉，部分结节状改变，余粘膜桔红色，散在点状充血水肿，皱襞形态及分布正常，粘液湖浅黄色，量中等。 胃角：弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，小弯侧见一直径约1cm溃疡，覆白苔，取病理1块送检，蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：球部上部见片状溃疡，覆白苔，降部粘膜未见异常。请给出可能的疾病名称。<|im_end|>\n<|im_start|>assistant\n', 大模型推理输出: ' 根据《中华人民共和国公司法》第一百三十八条的规定，有限责任公司股东会会议由股东按照出资比例行使表决权；但是，公司章程另有规定的除外。\n\n因此，股东会决议必须经代表三分之二以上表决权的股东通过。本题中，甲、乙、丙的出资额分别为30%、30%和40%，所以需要获得丙股东的同意才能通过该决议。\n\n综上所述，选项B是正确的。'

如上，原本模型是OK的，sft调完也OK，可能是什么原因呀

**Comment by liulan93** [comment]
{"chosen":[{"content":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管入口处可见一直径约1.2cm橘红色样上皮；距门齿约18cm可见一直径约0.3cm白色隆起，予活检钳钳除，取组织送检，余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖浑浊，量中等。 胃角：弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面光滑；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。 ","role":"user"},{"content":" 慢性非萎缩性胃炎,食管乳头状瘤,食管胃粘膜异位","role":"assistant"}],"rejected":[{"content":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管入口处可见一直径约1.2cm橘红色样上皮；距门齿约18cm可见一直径约0.3cm白色隆起，予活检钳钳除，取组织送检，余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖浑浊，量中等。 胃角：弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面光滑；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。 ","role":"user"},{"content":"胃癌,胃息肉,性胃炎,慢性萎缩性胃炎,汁反流性胃炎,胃溃疡,胃粘膜下肿物,胃静脉曲张,十二指肠溃疡,食管炎","role":"assistant"}],"prompt":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管入口处可见一直径约1.2cm橘红色样上皮；距门齿约18cm可见一直径约0.3cm白色隆起，予活检钳钳除，取组织送检，余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖浑浊，量中等。 胃角：弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面光滑；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。 "}
{"chosen":[{"content":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管距门齿约38cm可见一直径约0.6cm白色隆起；余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖清，量中等。 胃角：可见散在粘膜糜烂（患者无法配合取活检），弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面欠光滑，散在不规则隆起伴糜烂（患者无法配合取活检）；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。","role":"user"},{"content":" 慢性非萎缩性胃炎伴糜烂,食管肿物性质待查：平滑肌瘤？","role":"assistant"}],"rejected":[{"content":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管距门齿约38cm可见一直径约0.6cm白色隆起；余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖清，量中等。 胃角：可见散在粘膜糜烂（患者无法配合取活检），弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面欠光滑，散在不规则隆起伴糜烂（患者无法配合取活检）；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。","role":"user"},{"content":"胃癌,胃息肉,急性胃炎,慢性萎缩性胃炎,胆汁反流性胃炎,胃溃疡,胃粘膜下肿物,胃静脉曲张,十二指肠溃疡,食管乳头状瘤,食管胃粘膜异位,食管炎","role":"assistant"}],"prompt":" 你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：食管距门齿约38cm可见一直径约0.6cm白色隆起；余粘膜淡红色，表面光滑，齿状线清，贲门开闭正常。 胃底、胃体：粘膜桔红色，充血水肿，表面光滑，皱襞形态及分布正常，粘液湖清，量中等。 胃角：可见散在粘膜糜烂（患者无法配合取活检），弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，表面欠光滑，散在不规则隆起伴糜烂（患者无法配合取活检）；蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：粘膜未见异常。请给出可能的疾病名称。"}

补充训练数据样例

**Comment by mst272** [comment]
请问结果错误具体是什么错误，例如训练后的推理示例。另外，训练过程中相关指标如何。

**Comment by liulan93** [comment]
<img width="299" alt="微信图片_20240914083451" src="https://github.com/user-attachments/assets/0f12d9ed-b63d-4e12-a4e7-b2bddd5268a5">
感谢回复~这是loss曲线，结果错误是指推理的内容与prompt内容完全不相关（预训练模型及SFT微调，推理结果是相关的，会给出可能的胃部疾病名称），如下：
Prompt:
你现在是我的私人医生，有如下胃镜病历，需要你帮我诊断可能的疾病：食管、贲门：粘膜淡红色，表面散在白色斑片状物质附着，不易拭去，拭去后观察食管黏膜散在片状充血水肿，食管中下段见纵向暗蓝色静脉曲张，未见红色征及串珠样改变，齿状线清，贲门开闭正常。 胃底、胃体：胃底穹隆部见条状曲张静脉，部分结节状改变，余粘膜桔红色，散在点状充血水肿，皱襞形态及分布正常，粘液湖浅黄色，量中等。 胃角：弧形，软。 胃窦：粘膜不均匀桔红色，充血水肿，小弯侧见一直径约1cm溃疡，覆白苔，取病理1块送检，蠕动正常。 幽门：圆形，未见反流。 十二指肠球及降部：球部上部见片状溃疡，覆白苔，降部粘膜未见异常。请给出可能的疾病名称。

大模型推理输出:
 ' 根据《中华人民共和国公司法》第一百三十八条的规定，有限责任公司股东会会议由股东按照出资比例行使表决权；但是，公司章程另有规定的除外。\n\n因此，股东会决议必须经代表三分之二以上表决权的股东通过。本题中，甲、乙、丙的出资额分别为30%、30%和40%，所以需要获得丙股东的同意才能通过该决议。\n\n综上所述，选项B是正确的。'

**Comment by mst272** [comment]
抱歉，我目前是在做代码模型相关，文本模型相关问题并没有遇到过。
直觉上来讲应该是模型训蹦了，loss已经降为0了，可以调小一点学习率及训练轮数试试。另外，reject的数据是模型自己输出的吗？因为强化学习本质上是减少模型不好部分的输出，所以on-policy会比较好。

**Comment by liulan93** [comment]
> 抱歉，我目前是在做代码模型相关，文本模型相关问题并没有遇到过。 直觉上来讲应该是模型训蹦了，loss已经降为0了，可以调小一点学习率及训练轮数试试。另外，reject的数据是模型自己输出的吗？因为强化学习本质上是减少模型不好部分的输出，所以on-policy会比较好。

收到，我重新训练看看，非常感谢！

**Comment by liulan93** [comment]
> > 抱歉，我目前是在做代码模型相关，文本模型相关问题并没有遇到过。 直觉上来讲应该是模型训蹦了，loss已经降为0了，可以调小一点学习率及训练轮数试试。另外，reject的数据是模型自己输出的吗？因为强化学习本质上是减少模型不好部分的输出，所以on-policy会比较好。
> 
> 收到，我重新训练看看，非常感谢！

reject是参考病历内容，把不涉及的病种组织进去了，on-policy是啥意思呀

**Comment by mst272** [comment]
一般on policy可以理解为使用模型本身的回答做reject，off policy则反之
