### ISSUE TITLE
DPO训练损失不变

### ISSUE THREAD

**Issue by wangqian621** [mst272/LLM-Dojo#26]
Thanks for great job~
我参照项目所给的Qwen的DPO框架进行训练，仅仅是改成了Qwen-Audio的多模态输入，训练框架和项目一致。
但是训练出现loss不变的问题，设置过1e-7到1e-4的学习率都呈现上述问题。想问问可能是什么方面出现了错误。感谢！
![image](https://github.com/user-attachments/assets/77cf2317-67dd-4fa1-ae39-18618ef08f1e)

**Comment by mst272** [comment]
https://huggingface.co/docs/trl/dpo_trainer#special-considerations-for-vision-language-models
多模态的DPO可以参考一下这里

**Comment by wangqian621** [comment]
感谢！我之前有看过参考的链接，我是自己写的processor for
audio的代码（因为Qwen-audio好像不属于trl支持的VLM系列，虽然实际输入格式差不多），输入输出应该是对的，能够正常执行训练，所以我想问题并不出现在多了一个模态的数据上。由于我不太了解DPO训练设置，想问问有什么参数的错误设置有可能导致这个问题？再次感谢~

mst272 ***@***.***> 于2024年12月11日周三 15:46写道：

**Comment by mst272** [comment]
不好意思 多模态的我还没尝试过，但是这里有一个完整的示例， 你可以对照看一下参数等等
https://github.com/huggingface/trl/blob/main/examples/scripts/dpo_vlm.py

**Comment by wangqian621** [comment]
好的，非常感谢~~ btw，项目真的很棒！

mst272 ***@***.***> 于2024年12月11日周三 18:32写道：
