### ISSUE TITLE
请问下使用train_gkd保存后如何进行推理

### ISSUE THREAD

**Issue by lingq1** [mst272/LLM-Dojo#29]
使用train_gkd保存到LLM-Dojo/gkd-model2下，我要怎么进行合并权重，或者直接加载权重进行推理，我直接用llamafactory读取适配器会报错。

**Comment by mst272** [comment]
运行此目录下合并lora脚本`utils/script/merge_lora.py`，合并后即可正常推理。

**Comment by lingq1** [comment]
> 运行此目录下合并lora脚本`utils/script/merge_lora.py`，合并后即可正常推理。

感谢
