### ISSUE TITLE
Could not estimate the number of tokens of the input, floating-point operations will not be computed

### ISSUE THREAD

**Issue by ggbondcxl** [mst272/LLM-Dojo#5]
你好，我在利用dpo_multi计算时出现warings
```python
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
batch_eval_metrics=False,
beta=0.1,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
dataset_num_proc=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=./train_args/deepspeed_config/ds_config_zero2.json,
disable_dropout=True,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=no,
eval_use_gather_object=False,
evaluation_strategy=no,
f_alpha_divergence_coef=1.0,
f_divergence_type=FDivergenceType.REVERSE_KL,
force_use_ref_model=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generate_during_eval=False,
gradient_accumulation_steps=2,
gradient_checkpointing=True,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
is_encoder_decoder=None,
jit_mode_eval=False,
label_names=None,
label_pad_token_id=-100,
label_smoothing=0,
label_smoothing_factor=0.0,
learning_rate=0.0002,
length_column_name=length,
load_best_model_at_end=False,
local_rank=1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/hdd/u202320081001054/LLM-Dojo/output/runs/Jul27_14-24-24_gpu3,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=steps,
loss_type=sigmoid,
lr_scheduler_kwargs={},
lr_scheduler_type=constant_with_warmup,
max_grad_norm=1.0,
max_length=None,
max_prompt_length=None,
max_steps=-1,
max_target_length=None,
metric_for_best_model=None,
model_adapter_name=None,
model_init_kwargs=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=5000,
optim=paged_adamw_32bit,
optim_args=None,
optim_target_modules=None,
output_dir=/hdd/u202320081001054/LLM-Dojo/output,
overwrite_output_dir=False,
padding_value=0,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=16,
precompute_ref_log_probs=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
ref_adapter_name=None,
ref_model_init_kwargs=None,
ref_model_mixup_alpha=0.9,
ref_model_sync_steps=64,
reference_free=False,
remove_unused_columns=False,
report_to=['wandb'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
rpo_alpha=None,
run_name=/hdd/u202320081001054/LLM-Dojo/output,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=epoch,
save_total_limit=2,
seed=42,
skip_memory_metrics=True,
split_batches=None,
sync_ref_model=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
truncation_mode=keep_end,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=10,
weight_decay=0.0
```
以及是否能知道您在利用qwen2-7B训练多轮trl-internal-testing/hh-rlhf-helpful-base-trl-style时采用的max_length以及max_prompt_length

**Comment by ggbondcxl** [comment]
![Uploading 截屏2024-07-27 14.38.43.png…]()

**Comment by mst272** [comment]
可以忽略这个警告，它只是计算你训练期间完成的总FLOPS。max_length以及max_prompt_length设置为None其会自动设为128。loss为0可能不正常，需要进一步看一下是哪里的问题。

**Comment by ggbondcxl** [comment]
这是我的loss，我应该从哪里开始检查呢
<img width="488" alt="截屏2024-07-27 15 29 13" src="https://github.com/user-attachments/assets/e5d86096-b0fc-4935-aad6-e7e2d05c69dd">

**Comment by mst272** [comment]
> 这是我的loss，我应该从哪里开始检查呢 <img alt="截屏2024-07-27 15 29 13" width="488" src="https://private-user-images.githubusercontent.com/138103805/352707470-e5d86096-b0fc-4935-aad6-e7e2d05c69dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjU3NDEsIm5iZiI6MTcyMjA2NTQ0MSwicGF0aCI6Ii8xMzgxMDM4MDUvMzUyNzA3NDcwLWU1ZDg2MDk2LWIwZmMtNDkzNS1hYWQ2LWU3ZTJkMDVjNjlkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWIzNDYwMDdiMjFlYjIyYzMzY2E2ZmM0MGExNTlmZmE2NTIyYjJjMzU1NGI5OGQ2ZjAzYmViYWQxMjQ1ODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0yJlDieibDUDazsrebndCccpoeae6kKVJEDEIWpUmio">

可能是环境问题，peft==0.4.0，其他可以参考最新更新的requirement。

**Comment by ggbondcxl** [comment]
> > 这是我的loss，我应该从哪里开始检查呢 <img alt="截屏2024-07-27 15 29 13" width="488" src="https://private-user-images.githubusercontent.com/138103805/352707470-e5d86096-b0fc-4935-aad6-e7e2d05c69dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjU3NDEsIm5iZiI6MTcyMjA2NTQ0MSwicGF0aCI6Ii8xMzgxMDM4MDUvMzUyNzA3NDcwLWU1ZDg2MDk2LWIwZmMtNDkzNS1hYWQ2LWU3ZTJkMDVjNjlkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWIzNDYwMDdiMjFlYjIyYzMzY2E2ZmM0MGExNTlmZmE2NTIyYjJjMzU1NGI5OGQ2ZjAzYmViYWQxMjQ1ODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0yJlDieibDUDazsrebndCccpoeae6kKVJEDEIWpUmio">
> 
> 可能是环境问题，peft==0.4.0，其他可以参考最新更新的requirement。

您的python版本是多少呢，我利用conda进行安装

**Comment by ggbondcxl** [comment]
我尝试使用1000个epoch，当使用您提供的数据时100条，进度条显示15/1000，但当使用原版test数据集时，大概2354条，则显示15/37000，gradient_accumulation_steps*per_device_train_batch_size*gpus=8*4*2，这是为什么呢，loss由于时间关系我还在尝试

**Comment by ggbondcxl** [comment]
您好，当我使用的dpo_multi_data(100条）进行训练1000epochs，使用两块gpu，per_device_train_batch_size为16，gradient_accumulation_steps为2，应该是2*16*2为一次梯度回传，进度条显示29/2000 7个小时的时间，但是如果是当我使用的dpo_multi_data(100条）进行训练1000epochs，使用两块gpu，per_device_train_batch_size为8，gradient_accumulation_steps为4，应该是2*8*4为一次梯度回传，进度条显示29/1000 4个小时的时间，是出现了什么问题呢
