### ISSUE TITLE
关于多轮对话

### ISSUE THREAD

**Issue by aJupyter** [mst272/LLM-Dojo#6]
作者您好！我有两个问题：
- 目前框架貌似只支持单轮对话格式微调？
- system prompt好像也没法在数据集中更改？

**Comment by mst272** [comment]
问题1： 暂时还没支持多轮对话，不过近期会更新支持，或者你也可以提交一个pull :）
问题2暂时没懂是什么意思

**Comment by mst272** [comment]
> 作者您好！我有两个问题：
> 
> * 目前框架貌似只支持单轮对话格式微调？
> * system prompt好像也没法在数据集中更改？

已更新

**Comment by aJupyter** [comment]
多谢作者
