### ISSUE TITLE
RuntimeError: expected scalar type BFloat16 but found Half

### ISSUE THREAD

**Issue by BeSkyer** [mst272/LLM-Dojo#7]
Hello，I encountered a problem while following the tutorial for the experiment again：
Could not find the bitsandbytes CUDA binary at PosixPath('/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so')
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/trl/trainer/reward_trainer.py:175: UserWarning: When using RewardDataCollatorWithPadding, you should set `max_length` in RewardConfig. It will be set to `512` by default, but you should do it yourself in the future.
  warnings.warn(
  0%|                                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]You're using a Qwen2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:2906: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/root/autodl-tmp/LLM-Dojo-main/rlhf/reward_model.py", line 132, in <module>
    main()
  File "/root/autodl-tmp/LLM-Dojo-main/rlhf/reward_model.py", line 124, in main
    trainer.train()
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/transformers/trainer.py", line 2280, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/transformers/trainer.py", line 3350, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/accelerate/accelerator.py", line 2159, in backward
    loss.backward(**kwargs)
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/autodl-tmp/sftpy38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: expected scalar type BFloat16 but found Half
  0%|                                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
  
May I ask how to solve this problem? I tried to tokenize the dataset and convert it to bfloat16, but an error was reported: ValueError: type of 151552.0 unknown:<class'float '> Should be one of a python, numpy, pytorch or tensorflow object

**Comment by mst272** [comment]
Please send more specific configuration information, I run locally without errors. It could be an environmental issue or the machine does not support BF16.
